### ISSUE TITLE
IntervalTreeSet: TODO methods

### ISSUE THREAD

**Issue by safris** [openjax/btree#1]
- [ ] NavigableSet.descendingSet()
- [ ] NavigableSet.descendingIterator()
- [ ] NavigableSet.subSet(Interval,boolean,Interval,boolean)
- [ ] NavigableSet.subSet(Interval,Interval)
- [ ] NavigableSet.headSet(Interval,boolean)
- [ ] NavigableSet.headSet(Interval)
- [ ] NavigableSet.tailSet(Interval,boolean)
- [ ] NavigableSet.tailSet(Interval)
